apiVersion: apps/v1
kind: Deployment
metadata:
  name: provenance-deployment
  labels:
    app: provenance
spec:
  selector:
    matchLabels:
      app: provenance
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: provenanceio/provenance:v1.5.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1317
        - containerPort: 9090
        - containerPort: 26656
        - containerPort: 26657
        command: ["sh"]
        args: ["/home/provenance/seed/custom_entrypoint.sh"]
        volumeMounts:
        - name: provenance-data
          mountPath: /home/provenance/data
        - name: provenance-config
          mountPath: /home/provenance/config
        - name: provenance-config-seed
          mountPath: /home/provenance/seed
        env:
          - name: ID
            value: ""
          - name: LOG
            value: -provenanced.log
      volumes:
      - name: provenance-data
        persistentVolumeClaim:
          claimName: provenance-data-claim
      - name: provenance-config
        persistentVolumeClaim:
          claimName: provenance-config-claim
      - name: provenance-config-seed
        configMap:
          name: provenance-config