apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p8e-local

bases:
  - ../base
  - ./elasticsearch
  - ./p8e-postgres
  - ./provenance
  - ./jaeger

resources:
  - namespace.yaml

patchesStrategicMerge:
  - ./p8e/deployment.yaml
  - ./p8e/p8e-secret.yaml
  - ./p8e/p8e-migration-secret.yaml
  - ./p8e-ui/p8e-ui-env.yaml

configMapGenerator:
  - name: keys-sql
    files:
    - p8e/keys.sql
    - p8e/init_keys.sh