apiVersion: v1
kind: Service
metadata:
  name: jaeger-udp
  labels:
    app: jaeger
spec:
  type: LoadBalancer
  selector:
    app: jaeger
  ports:
    - protocol: UDP
      name: jaeger-http-tracing
      port: 6831
      targetPort: 6831