apiVersion: apps/v1
kind: Deployment
metadata:
  name: p8e-deployment
  labels:
    app: p8e-api
spec:
  selector:
    matchLabels:
      app: p8e-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: p8e-api
    spec:
      containers:
      - name: p8e
        image: ghcr.io/provenance-io/p8e-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common
        - secretRef:
            name: common
        - configMapRef:
            name: p8e-api
        - secretRef:
            name: p8e-api
      initContainers:
      - name: p8e-migration
        image: ghcr.io/provenance-io/p8e-migration:m1-fix # need a fix to the base flyway image used in order to switch this to latest
        imagePullPolicy: Always
        args: ["migrate"]
        envFrom:
          - configMapRef:
              name: common
          - configMapRef:
              name: p8e-migration
          - secretRef:
              name: p8e-migration